# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            DSSG Project Name
tagline:          ''
url:              "https://atasayin.github.io/"
baseurl:          "/DSSG-website-template"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:          https://github.com/atasayin/atasayin.github.io/
